# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: true
cache: packages
before_install:
  - sudo add-apt-repository -y ppa:nschloe/hdf5-backports
  - sudo apt-get update
  - sudo apt-get install -y libhdf5-dev
  - h5cc -showconfig
  - Rscript -e 'source("https://bioconductor.org/biocLite.R");biocLite(c("multtest", "survival", "MASS"), ask = FALSE)'
addons:
  apt:
    update: true

use_bioc: true

r_packages:
  - covr
  - hdf5r

# enable remotes
r_github_packages:
- TomKellyGenetics/Rphenograph
- TomKellyGenetics/heatmap.2x

after_success:
  - Rscript -e 'library(covr); codecov()'

env:
  global:
    - R_CHECK_ARGS="--no-build-vignettes --no-manual --timings"
    - _R_CHECK_TIMINGS_="0"
