# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
before_install:
  - sudo apt-get update
  - sudo apt-get install -y libhdf5-dev
  - sudo apt-get install -y libhdf5=1.8.12
  - h5cc -showconfig

r_packages:
  - covr
  - hdf5r

after_success:
  - Rscript -e 'library(covr); codecov()'
