# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: true
cache: packages
before_install:
  - sudo apt-get update
  - sudo apt-get install -y libhdf5-dev
  - h5cc -showconfig
addons:
  apt:
    update: true

r_packages:
  - covr
  - hdf5r

after_success:
  - Rscript -e 'library(covr); codecov()'
